Update depends for cowboy v.2
pezra/phoenix_cowboy_logging pull request #1
Opened 2020-04-15 09:07 UTC by UA3MQJ

2020-04-24 19:40 UTC, pezra requested changes
@UA3MQJ thanks for the contribution. Looks good except for the inline comment.

2020-04-24 19:40 UTC, pezra commented on mix.exs
> +     version: "1.0.1",
```suggestion
     version: "2.0.0",
```
This seems like a breaking change because it bumps the required major version of cowboy. Am i interpreting that correctly?

2020-04-27 14:17 UTC, UA3MQJ commented on mix.exs
> +     version: "1.0.1",
I agree

2020-05-27 12:40 UTC, UA3MQJ commented
Up

2020-05-27 18:17 UTC, pezra approved these changes

2020-05-27 18:17 UTC, merged

2020-05-27 18:21 UTC, pezra commented
released a version 2.0.0. thanks!